jobs:
- job: Windows
  pool:
    vmImage: 'VS2017-Win2016'
  timeoutInMinutes: 150
  variables:
    GRADLE_USER_HOME: $(Pipeline.Workspace)/.gradle
  steps:
  - checkout: self
    submodules: true
  - task: NodeTool@0
    inputs:
      versionSpec: '8.12.0'
  - task: CacheBeta@0
    inputs:
      key: gradle | $(Agent.OS)
      path: $(GRADLE_USER_HOME)
    displayName: Gradle build cache
  - script: |
      ./gradlew -Dorg.gradle.parallel=false :testerina-integration-test:test -x createJavadoc --stacktrace -scan --console=plain --no-daemon
    displayName: 'Ballerina Windows Build'