/*
 *  Copyright (c) 2020, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
 *
 *  WSO2 Inc. licenses this file to you under the Apache License,
 *  Version 2.0 (the "License"); you may not use this file except
 *  in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an
 *  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 *  KIND, either express or implied.  See the License for the
 *  specific language governing permissions and limitations
 *  under the License.
 */
package io.ballerina.cli.cmd;

import io.ballerina.cli.BLauncherCmd;
import io.ballerina.cli.TaskExecutor;
import io.ballerina.cli.task.CleanTargetDirTask;
import io.ballerina.cli.task.CompileTask;
import io.ballerina.cli.task.CreateDocsTask;
import io.ballerina.cli.task.ResolveMavenDependenciesTask;
import io.ballerina.cli.task.RunBuildToolsTask;
import io.ballerina.projects.BuildOptions;
import io.ballerina.projects.ProjectEnvironmentBuilder;
import io.ballerina.projects.ProjectException;
import io.ballerina.projects.ProjectKind;
import io.ballerina.projects.Workspace;
import io.ballerina.projects.bala.BalaProject;
import io.ballerina.projects.repos.TempDirCompilationCache;
import io.ballerina.projects.util.ProjectConstants;
import io.ballerina.projects.util.ProjectPaths;
import org.ballerinalang.docgen.docs.BallerinaDocGenerator;
import picocli.CommandLine;

import java.io.IOException;
import java.io.PrintStream;
import java.nio.file.Path;
import java.util.List;
import java.util.Optional;

import static io.ballerina.cli.cmd.Constants.DOC_COMMAND;

/**
 * This class represents the "bal doc" command.
 *
 * @since 2.0.0
 */
@CommandLine.Command(name = DOC_COMMAND, description = "Generate current package's documentation")
public class DocCommand implements BLauncherCmd {

    private final PrintStream outStream;
    private final PrintStream errStream;
    private Path projectPath;
    private Path outputPath;
    private final boolean exitWhenFinish;

    public DocCommand() {
        this.projectPath = Path.of(System.getProperty("user.dir"));
        this.outStream = System.out;
        this.errStream = System.err;
        this.exitWhenFinish = true;
    }

    DocCommand(PrintStream outStream, PrintStream errStream, boolean exitWhenFinish) {
        this.projectPath = Path.of(System.getProperty("user.dir"));
        this.outStream = outStream;
        this.errStream = errStream;
        this.exitWhenFinish = exitWhenFinish;
        this.offline = true;
    }

    DocCommand(PrintStream outStream, PrintStream errStream, boolean exitWhenFinish, Path targetDir) {
        this.projectPath = Path.of(System.getProperty("user.dir"));
        this.outStream = outStream;
        this.errStream = errStream;
        this.exitWhenFinish = exitWhenFinish;
        this.targetDir = targetDir;
        this.offline = true;
    }

    @CommandLine.Option(names = {"--o", "-o"}, description = "Location to save API Docs.")
    private String outputLoc;

    @CommandLine.Option(names = {"--combine", "-combine"}, description = "Creates index using modules.")
    private boolean combine;

    @CommandLine.Option(names = {"--offline"}, description = "Compiles offline without downloading " +
            "dependencies.")
    private Boolean offline;

    @CommandLine.Option(names = "--old-parser", description = "Enable old parser.", hidden = true)
    private boolean useOldParser;

    @CommandLine.Parameters
    private List<String> argList;

    @CommandLine.Option(names = {"--exclude", "-e"}, description = "List of modules to be excluded.")
    private String[] excludes;

    @CommandLine.Option(names = {"--help", "-h"}, hidden = true)
    private boolean helpFlag;

    @CommandLine.Option(names = "--experimental", description = "Enable experimental language features.")
    private boolean experimentalFlag;

    @CommandLine.Option(names = "--target-dir", description = "target directory path")
    private Path targetDir;

    @CommandLine.Option(names = "--disable-syntax-tree-caching", hidden = true, description = "disable syntax tree " +
            "caching for source files", defaultValue = "false")
    private Boolean disableSyntaxTreeCaching;

    @CommandLine.Option(names = "--show-dependency-diagnostics", description = "Show the diagnostics " +
            "generated by the dependencies")
    private Boolean showDependencyDiagnostics;

    @CommandLine.Option(names = "--optimize-dependency-compilation", hidden = true,
            description = "experimental memory optimization for large projects")
    private Boolean optimizeDependencyCompilation;

    @Override
    public void execute() {
        if (this.helpFlag) {
            String commandUsageInfo = BLauncherCmd.getCommandUsageInfo(DOC_COMMAND);
            this.errStream.println(commandUsageInfo);
            return;
        }
        if (argList == null) {
            this.projectPath = Path.of(System.getProperty("user.dir"));
        } else {
            // Generate docs from a bala
            if (argList.get(0).endsWith(".bala")) {
                this.projectPath = Path.of(System.getProperty("user.dir"));
                Path balaPath = this.projectPath.resolve(argList.get(0));
                Workspace workspace = Workspace.load(balaPath);
                try {
                    BallerinaDocGenerator.generateAPIDocs(
                            workspace.packages().iterator().next(), this.projectPath.toString(), false);
                } catch (IOException e) {
                    CommandUtil.printError(this.errStream, e.getMessage(), null, false);
                    CommandUtil.exitError(this.exitWhenFinish);
                    return;
                }
                return;
            }
            this.projectPath = Path.of(argList.get(0));
        }
        // combine docs
        if (this.combine) {
            outStream.println("Combining Docs");
            BallerinaDocGenerator.mergeApiDocs(this.projectPath);
            if (this.exitWhenFinish) {
                Runtime.getRuntime().exit(0);
            }
        }

        if (this.argList != null && this.argList.get(0).endsWith(ProjectConstants.BLANG_SOURCE_EXT)) {
            CommandUtil.printError(this.errStream,
                    "generating API Documentation is not supported for a single Ballerina file.",
                    null,
                    false);
            CommandUtil.exitError(true);
            return;
        }

        // check if there are too many arguments.
        if (this.argList != null && this.argList.size() > 1) {
            CommandUtil.printError(this.errStream,
                    "too many arguments",
                    "bal doc <project_path> [--offline]\n",
                    false);
            CommandUtil.exitError(true);
            return;
        }

        if (ProjectPaths.isWorkspaceRoot(this.projectPath)) {
            CommandUtil.printError(this.errStream,
                    "the specified path is a workspace, please specify a package or a source file to run",
                    null, true);
            CommandUtil.exitError(this.exitWhenFinish);
            return;
        } else if (!ProjectPaths.isPackageRoot(this.projectPath)) {
            CommandUtil.printError(this.errStream,
                    "the specified path is not a valid Ballerina package: "
                            + this.projectPath.toAbsolutePath(), null, true);
            CommandUtil.exitError(this.exitWhenFinish);
            return;
        }

        Optional<Path> workspaceRoot = ProjectPaths.findWorkspaceRoot(this.projectPath);
        BuildOptions buildOptions = constructBuildOptions(workspaceRoot.isPresent());

        Workspace workspace;
        try {
            workspace = workspaceRoot.map(path -> Workspace.load(path, buildOptions)).orElseGet(()
                    -> Workspace.load(this.projectPath, buildOptions));
        } catch (ProjectException e) {
            CommandUtil.printError(this.errStream, "failed to load the workspace: " + e.getMessage(), null, false);
            CommandUtil.exitError(this.exitWhenFinish);
            return;
        }

        if (workspace.kind() == ProjectKind.WORKSPACE_PROJECT) {
            if (targetDir != null) {
                CommandUtil.printError(this.errStream,
                        "'--target-dir' is not supported for workspaces", null, true);
                CommandUtil.exitError(this.exitWhenFinish);
                return;
            }
        }

        // normalize paths
        this.projectPath = this.projectPath.toAbsolutePath().normalize();
        this.outputPath = this.outputLoc != null ? Path.of(this.outputLoc).toAbsolutePath() : null;

        if (!workspaceRoot.orElseThrow().equals(this.projectPath)) {
            generateDocsForSpecificProject(workspace);
        }
    }

    private void generateDocsForSpecificProject(Workspace workspace) {
        TaskExecutor taskExecutor = new TaskExecutor.TaskBuilder()
                .addTask(new CleanTargetDirTask(this.projectPath)) // create target directory.
                .addTask(new RunBuildToolsTask(outStream, this.projectPath)) // run build tools
                .addTask(new ResolveMavenDependenciesTask(outStream, this.projectPath)) // resolve maven dependencies in Ballerina.toml
                .addTask(new CompileTask(outStream, errStream, this.projectPath)) // compile the modules
                .addTask(new CreateDocsTask(outStream, outputPath, this.projectPath)) // creates API documentation
                .build();

        taskExecutor.executeTasks(workspace);
        if (this.exitWhenFinish) {
            Runtime.getRuntime().exit(0);
        }
    }

    @Override
    public String getName() {
        return DOC_COMMAND;
    }

    @Override
    public void printLongDesc(StringBuilder out) {
        out.append(BLauncherCmd.getCommandUsageInfo(DOC_COMMAND));
    }

    @Override
    public void printUsage(StringBuilder out) {
        out.append("  bal doc \n");
    }

    @Override
    public void setParentCmdParser(CommandLine parentCmdParser) {
    }

    private BuildOptions constructBuildOptions(boolean workspaceBuild) {
        BuildOptions.BuildOptionsBuilder buildOptionsBuilder = BuildOptions.builder();

        buildOptionsBuilder
                .setCodeCoverage(false)
                .setExperimental(experimentalFlag)
                .setOffline(offline)
                .setTestReport(false)
                .setObservabilityIncluded(false)
                .disableSyntaxTreeCaching(disableSyntaxTreeCaching)
                .setShowDependencyDiagnostics(showDependencyDiagnostics)
                .setOptimizeDependencyCompilation(optimizeDependencyCompilation);

        if (targetDir != null && workspaceBuild) {
            buildOptionsBuilder.targetDir(targetDir.toString());
        }

        return buildOptionsBuilder.build();
    }
}
